 [azure]
 form_recognizer_endpoint = "https://ppedv-rag-chatbot-di.cognitiveservices.azure.com/"
 form_recognizer_key = "2990RWVY4a5zIPUV5MkI56hVSVoQMhEQQk8jvbt8pPX3BQ1RU8zTJQQJ99ALACYeBjFXJ3w3AAALACOGTRR5"